server:
  port: 8761
spring:
  application:
    name: eureka-server
  threads:
    virtual:
      enabled: true
eureka:
  instance:
    hostname: eureka-server
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${{eureka.instance.hostname}}:${{server.port}}/eureka/
  server:
    enable-self-preservation: false
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
